spring:
  config:
    activate:
      on-profile: env-local

  main:
    deferred-initialization: true
    deferred-datasource-initialization-mode: create

  jpa:
    hibernate:
      ddl-auto: create-drop
    show_sql: true
    properties:
      hibernate:
        format_sql: true


  datasource:
    url: jdbc:h2:mem:~/testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 100

  redis:
    host: localhost
    port: 6879

  h2:
    console:
      enabled: true


jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  accessToken-validity-in-seconds: 3600 # 1시간
  refreshToken-validity-in-seconds: 18000 # 5시간

jwt.refreshToken-validity-in-seconds: 1800


