spring:
  config:
    profiles:
      group:
        local: env-local

---
spring:
  config:
    activate:
      on-profile: env-local
  redis:
    host: localhost
    port: 6879
  jpa:
    properties:
      hibernate:
        show_sql: true

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  accessToken-validity-in-seconds: 3600 # 1시간
  refreshToken-validity-in-seconds: 18000 # 5시간