spring:
  config:
    profiles:
      group:
        local: env-local

---
spring:
  main:
    deferred-initialization: true
    deferred-datasource-initialization-mode: create

  jpa:
    hibernate:
      ddl-auto: create-drop
      show_sql: true
      format_sql: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 100

  config:
    activate:
      on-profile: env-local

  redis:
    host: localhost
    port: 6879








jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  accessToken-validity-in-seconds: 3600 # 1시간
  refreshToken-validity-in-seconds: 18000 # 5시간